version: '3'
services:
  backend.kibe:
    container_name: backend.kibe
    build:
      context: backend-kibe
      dockerfile: Dockerfile
    networks:
      - kibe-network
    ports:
      - 8080:8080
  frontend.kibe:
    container_name: frontend.kibe
    build:
      context: frontend-kibe
      dockerfile: Dockerfile
    depends_on:
      - backend.kibe
    networks:
      - kibe-network
    ports:
    - 8081:8080

networks:
  kibe-network: