# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: End to end test with docker containers

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  
  dockerize:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Run containers
      run: docker-compose up -d --build
  test:
    runs-on: ubuntu-latest
    needs: dockerize
    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run end-to-end tests
      run: mvn test -pl end-to-end
  
  teardown:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Stop containers
        run: docker-compose down
